name: "Steve's Photography"
favicon: null
layout_spectrum: 0.30705039016902447
typography_spectrum: 0.4952772257383913
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.15021037869155407
  lightness: 0.8801033038180321
  saturation: 0.04404534446075559
  rhythmicContrast: 0.9310413640923798
purpose: []
